### ISSUE TITLE
New Features

### ISSUE THREAD

**Issue by ghost** [ledbetterljoshua/annoyingmicah#13]
The investors feel like this product isn't getting enough traction yet. So, even though we haven't done any user studies, or really gotten any feedback or feature request, I'm thinking we should try to build some super-cool-super-big-feature-that-3-people-will-use??

@ledbetterljoshua & @mrled, let me know your thoughts by EOD, I want to get user stories written before our 7:45am standup tomorrow.

**Comment by mrled** [comment]
7:45 sure as long as that's in AUSTRALIAN TIME because otherwise I'm gonna be hung over

**Comment by mrled** [comment]
I think we should solicit ideas from the community. @jowj, do you have any insight for our team here?

**Comment by ledbetterljoshua** [comment]
I got one. Lets add an initial page that allows the user to type out a message. Once they submit the message they are taken to the main page which shows their message and the classic star wars joke we all know and love. Users can then share it with their friends!! I think this is ground breaking guys

**Comment by mrled** [comment]
Or more like ;) space breaking ;) because Start Wars is set in space ;)

**Comment by ledbetterljoshua** [comment]
Omg @mrled you are so smart 💯

**Comment by ledbetterljoshua** [comment]
But actually adding this lol

**Comment by jowj** [comment]
look guys, the investors are right to be worried. we are relevent for only 1 month of the year!!! we need to expand this format to include all months.

March Towards the Ninth!
This August (10th) Occasion!

This way we can increase our Web Footprint (tm) and reduce pull from other platforms on our userbase

**Comment by mrled** [comment]
Haha wow @jowj it seems like you are pretttttttttttttty far behind, we can already say "DECEMBER THE 25TH BE WITH YOU" etc for Christmas holidays ;) maybe next time you can do a little more research before submitting your "feed back"

**Comment by jowj** [comment]
holy shit

**Comment by jowj** [comment]
Ok in my defense last time I opened it all i saw was josh's terrible variable names and then closed the tab.

I will do More Research in the Future.

**Comment by mrled** [comment]
In the future please refrain from defending yourself when you're attacked by one of the Founders, they are special snowflakes and should never be questioned under any circumstances

**Comment by ledbetterljoshua** [comment]
@mrled the feature has been added

**Comment by mrled** [comment]
Vote to close then

**Comment by ledbetterljoshua** [comment]
But first the feature needs to be pushed live for our clients. The investors need results!

**Comment by mrled** [comment]
Hey @hannahlindsley we want to invite you to collaborate with us on this important projecT! :)

**Comment by ghost** [comment]
This is LIVE NOW, +1 vote to close!
