### ISSUE TITLE
IE 4.0 (Classic Mac OS) support

### ISSUE THREAD

**Issue by mrled** [ledbetterljoshua/annoyingmicah#16]
Hi guys, I'm not able to test this on Internet Exploer 4.0 for Mac OS 9 because I don't have a Mac or a computer at all, but I'm hoping it works. Someone please let me know, thanks

**Comment by ghost** [comment]
@mrled have you tried building a VM by hand, in the cloud, to test this?? Also I think we need to talk about what versions of IE we support. 40% of our users are still on 4.0 so obviously we should continue to support that, but the numbers are small for 1.0 and 2.0, I think we should consider dropping those.

**Comment by mrled** [comment]
No, I'm unable to do this currently because I don't have a computer or even a cloud, I just want it to work. Was hoping the dev team would be able to handle this one?

**Comment by ghost** [comment]
Sorry, the only dev team members who can handle this are in India so they are asleep right now, plz file an official request and we will put it in the Kanban queue, which currently has an estimated turnaround time of 3 weeks - 6 months.

**Comment by mrled** [comment]
OK thanks, that's exactly what I needed
